[package]
name = "common-exception"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
common-arrow = { path = "../arrow" }

anyhow = "1.0.44"
backtrace = "0.3.62"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.30"
tonic = "0.5.2"
prost = "0.9.0"
paste = "^1.0"

# Github dependencies
sqlparser = { git = "https://github.com/datafuse-extras/sqlparser-rs", rev = "cdd2ce1" }
