[package]
name = "databend-common-pipeline-transforms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
databend-common-base = { path = "../../../common/base" }
databend-common-exception = { path = "../../../common/exception" }
databend-common-expression = { path = "../../expression" }
databend-common-pipeline-core = { path = "../core" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }
jsonb = { workspace = true }
match-template = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }

[dev-dependencies]
itertools = { workspace = true }
rand = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["match-template"]
