[package]
name = "databend-common-tracing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
databend-common-base = { workspace = true }
databend-common-exception = { workspace = true }
defer = "0.2"
fern = "0.6.2"
humantime = "2.1.0"
itertools = { workspace = true }
log = { workspace = true }
minitrace = { workspace = true }
minitrace-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tonic = { workspace = true }
tracing-appender = { workspace = true }
rdkafka = { version = "0.36", default-features = false, features = ["tokio"] }

[dev-dependencies]

[lints]
workspace = true
