[package]
name = "common-tracing"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
lazy_static = "1.4.0"
opentelemetry = { version = "0.16", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.15", features = ["rt-tokio"] }
tonic = "0.5.2"
tracing = "0.1.29"
tracing-appender = "0.2.0"
tracing-bunyan-formatter = "0.2"
tracing-opentelemetry = "0.15.0"
tracing-subscriber = "0.2.25"
